## General Kubernetes configuration values.
Kubernetes:
  Namespace:
    Enabled: false
    # Namespace name where this chart is to be deployed to
    Name: "devops"
    # When true, namespaces are not deleted when the release is deleted.
    KeepNamespaces: true

Master:
  Name: master
  Image: "xfrarod/jenkins-master"
  Namespace: "devops"
  ImageTag: "2.107.2"
  ImagePullPolicy: "Always"
  ImagePullSecret: bc-devops
  Component: "master"
  UseSecurity: true
  AdminUser: admin
  AdminPassword: "admin123!"
  Cpu: "200m"
  Memory: "250Mi"
  ServicePort: 443
  # For minikube, set this to NodePort, elsewhere use LoadBalancer
  # Use ClusterIP if your setup includes ingress controller
  ServiceType: LoadBalancer
  ContainerPort: 8080
  # Enable Kubernetes Liveness and Readiness Probes
  HealthProbes: false
  HealthProbesTimeout: 60
  # ~2 minutes to allow Jenkins to restart when upgrading plugins
  HealthProbeLivenessFailureThreshold: 12
  SlaveListenerPort: 50000
  # Kubernetes service type for the JNLP slave service
  # SETTING THIS TO "LoadBalancer" IS A HUGE SECURITY RISK: https://github.com/kubernetes/charts/issues/1341
  SlaveListenerServiceType: ClusterIP
  SlaveListenerServiceAnnotations: {}
  LoadBalancerSourceRanges:
  - 0.0.0.0/0
  CustomConfigMap: false
  NodeSelector: {}
  Tolerations: {}

Slave:
  Name: slave
  Mode: exclusive
  Desc: "Core Jenkins Slave"
  Labels: "swarm slave helm kubectl"
  Executors: 1
  Replicas: 1
  Image: "xfrarod/jenkins-slave"
  ImageTag: "1.0.0"
  ImagePullPolicy: "Always"
  ImagePullSecret: bc-devops
  Component: "slave"
  JavaOpts: "-Djava.awt.headless=true"

  Resources:
   limits:
     cpu: 1000m
     memory: 1Gi
   requests:
     cpu: 400m
     memory: 1Gi

Agent:
  Enabled: false
  Image: xfrarod/jenkins-slave
  ImageTag: 1.0.0
  Component: "slave"
  Privileged: false
  Cpu: "200m"
  Memory: "256Mi"
  # You may want to change this to true while testing a new image
  AlwaysPullImage: false

Persistence:
  Master:
    Enabled: true
    Annotations: {}
    AccessMode: ReadWriteOnce
    Size: 5Gi
    StorageClassName: hostpath

  Slave:
    Enabled: true
    AccessMode: ReadWriteOnce
    Size: 5Gi
    StorageClassName: hostpath

NetworkPolicy:
  # Enable creation of NetworkPolicy resources.
  Enabled: false
  # For Kubernetes v1.4, v1.5 and v1.6, use 'extensions/v1beta1'
  # For Kubernetes v1.7, use 'networking.k8s.io/v1'
  ApiVersion: extensions/v1beta1

## Install Default RBAC roles and bindings
rbac:
  install: false
  serviceAccountName: default
  # RBAC api version (currently either v1beta1 or v1alpha1)
  apiVersion: v1beta1
  # Cluster role reference
  roleRef: cluster-admin
